---
title: "Introduction to `shiny`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 9.2: Our First `shiny` App

Exercise 1: Creating a reactive app that says hello to user

```{r}
library(shiny)

ui <- fluidPage(
  textInput("name", "What's your name?"), 
  textOutput("greeting")
)

server <- function(input, output, session) {
  output$greeting <- renderText({
  paste0("Hello ", input$name)
})
}

shinyApp(ui, server)
```

Exercise 2: Fixing app to display 5 times number chosen in slider bar

```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", label = "If x is", min = 1, max = 50, value = 30),
  "then x times 5 is",
  textOutput("product")
)

server <- function(input, output, session) {
  output$product <- renderText({ 
    input$x * 5
  })
}

shinyApp(ui, server)
```

Exercise 3: Creating new variable y with slider and creating product between x and y

```{r}
ui <- fluidPage(
  sliderInput("x", label = "If x is", min = 1, max = 50, value = 30), 
  sliderInput("y", label = "and y is", min = 1, max = 50, value = 5), 
  "then x times y is",
  textOutput("product")
)

server <- function(input, output, session) {
  output$product <- renderText({ 
    input$x * input$y
  })
}

shinyApp(ui, server)
```

Exercise 4: Fixing app code to make it shorter

```{r}
library(shiny)

ui <- fluidPage(
  sliderInput("x", "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", "and y is", min = 1, max = 50, value = 5),
  "then, (x * y) is", textOutput("product"),
  "and, (x * y) + 5 is", textOutput("product_plus5"),
  "and (x * y) + 10 is", textOutput("product_plus10")
)

server <- function(input, output, session) {
  product <- reactive({
    input$x * input$y
  })
  output$product <- renderText({ 
    product()
  })
  output$product_plus5 <- renderText({ 
    product() + 5
  })
  output$product_plus10 <- renderText({ 
    product() + 10
  })
}

shinyApp(ui, server)
```
